import type { AddOn, Booking } from "@/types";

// Mocked bookings for the Noosa trip. Refs are realistic-format but fake.
// Mix of confirmed and to-book so the Bookings tab feels live.
export const BOOKINGS: Booking[] = [
  {
    id: "bk-flight-out",
    type: "flight",
    icon: "✈️",
    title: "AKL → Sunshine Coast",
    detail: "Air New Zealand · NZ on-time · 08:05",
    status: "confirmed",
    ref: "NZ-4QJ8KP",
    day: 1,
    cost_nzd: 1180,
  },
  {
    id: "bk-car",
    type: "car",
    icon: "🚗",
    title: "Hire car — compact SUV",
    detail: "Sunshine Coast Airport · 4 days",
    status: "confirmed",
    ref: "AVS-7781234",
    day: 1,
    cost_nzd: 520,
  },
  {
    id: "bk-hotel",
    type: "hotel",
    icon: "🏨",
    title: "Netanya Noosa",
    detail: "Hastings Street · 7 nights · ocean view",
    status: "confirmed",
    ref: "NET-2026-1101",
    day: 1,
    cost_nzd: 3150,
  },
  {
    id: "bk-bistroc",
    type: "dining",
    icon: "🍽️",
    title: "Bistro C — dinner",
    detail: "Day 1 · 7:00pm · table for 2",
    status: "confirmed",
    ref: "BC-118842",
    day: 1,
    cost_nzd: 150,
  },
  {
    id: "bk-locale",
    type: "dining",
    icon: "🍝",
    title: "Locale Noosa — dinner",
    detail: "Day 2 · 7:30pm · table for 2",
    status: "confirmed",
    ref: "LOC-90455",
    day: 2,
    cost_nzd: 200,
  },
  {
    id: "bk-kayak",
    type: "activity",
    icon: "🛶",
    title: "Kanu Kapers — Everglades day tour",
    detail: "Day 3 · 9:30am · 2 guests",
    status: "confirmed",
    ref: "KK-EVG-3311",
    day: 3,
    cost_nzd: 320,
  },
  {
    id: "bk-sumyung",
    type: "dining",
    icon: "🥢",
    title: "Sum Yung Guys — dinner",
    detail: "Day 6 · 7:00pm · the one not to miss",
    status: "to_book",
    ref: null,
    day: 6,
    cost_nzd: 200,
  },
  {
    id: "bk-dreamboats",
    type: "activity",
    icon: "⛵",
    title: "Noosa Dreamboats — electric picnic boat",
    detail: "Day 6 · 9:30am · 2 hours",
    status: "to_book",
    ref: null,
    day: 6,
    cost_nzd: 180,
  },
  {
    id: "bk-sails",
    type: "dining",
    icon: "🦪",
    title: "Sails — long lunch",
    detail: "Day 5 · 1:00pm · beachfront edge",
    status: "to_book",
    ref: null,
    day: 5,
    cost_nzd: 220,
  },
  {
    id: "bk-moneypennys",
    type: "dining",
    icon: "🍸",
    title: "Miss Moneypenny's — farewell dinner",
    detail: "Day 7 · 7:00pm · table for 2",
    status: "to_book",
    ref: null,
    day: 7,
    cost_nzd: 180,
  },
  {
    id: "bk-flight-home",
    type: "flight",
    icon: "✈️",
    title: "Sunshine Coast → AKL",
    detail: "Day 8 · 2:10pm · return",
    status: "to_book",
    ref: null,
    day: 8,
    cost_nzd: 0,
  },
];

export const ADDONS: AddOn[] = [
  {
    key: "esim",
    icon: "📶",
    title: "Stay connected in Australia",
    subtitle: "Local data, activated before you land",
    description:
      "Skip the roaming charges. A local data plan means your maps, messages and bookings work from the moment you step off at Sunshine Coast.",
    price: "From NZD $19",
    priceNote: "10 days · Australia coverage",
    cta: "Add eSIM",
    tag: "Recommended",
    cost: 19,
  },
  {
    key: "insurance",
    icon: "🛡️",
    title: "Travel insurance",
    subtitle: "Medical, cancellation and baggage cover",
    description:
      "Covers the unexpected — medical, cancelled flights, lost luggage and trip interruption. Your dates and destination are already set.",
    price: "From NZD $72",
    priceNote: "7 nights · 2 adults · Australia",
    cta: "Get covered",
    tag: "Recommended",
    cost: 72,
  },
  {
    key: "fx",
    icon: "💳",
    title: "Travel money card",
    subtitle: "Spend in AUD with no foreign transaction fees",
    description:
      "Load AUD before you go and spend at the real exchange rate. No fees at ATMs or on contactless across Queensland.",
    price: "No card fee",
    priceNote: "Exchange rate applies",
    cta: "Get card",
    cost: 0,
  },
  {
    key: "transfer",
    icon: "🚐",
    title: "Airport transfer",
    subtitle: "Sunshine Coast Airport → Hastings Street · 1 Nov",
    description:
      "Prefer not to drive on day one? Meet and greet at arrivals, fixed price, fits 2 with luggage. (You can still hire a car for the Everglades and hinterland days.)",
    price: "NZD $85",
    priceNote: "Fixed price · 1 Nov",
    cta: "Book transfer",
    cost: 85,
  },
];
